import type { MDXContent } from 'mdx/types';
import type { TOCItemType } from 'fumadocs-core/toc';
// Generated by fumadocs-mdx into the project root `.source` (see source.config.ts).
import { blog } from '../../.source/server';
import { publicConfig } from '@/lib/public-config';

export { absoluteUrl, crossPostMarkdown, formatDate } from '@/lib/blog-markdown';

export interface Post {
  slug: string;
  /** Its path on the site, /blog/<slug>. */
  url: string;
  title: string;
  description: string;
  /** YYYY-MM-DD. */
  date: string;
  updated?: string;
  author: string;
  versions: string;
  tags: string[];
  next: { label: string; href: string };
  draft: boolean;
  body: MDXContent;
  toc: TOCItemType[];
  /** The post's file as written, frontmatter and all. */
  source: () => Promise<string>;
  /** The post's Markdown as written, without its frontmatter. */
  markdown: () => Promise<string>;
}

const all: Post[] = blog
  .map((entry) => {
    const slug = entry.info.path.replace(/\.mdx?$/, '');
    return {
      slug,
      url: `/blog/${slug}`,
      title: entry.title,
      description: entry.description,
      date: entry.date,
      updated: entry.updated,
      author: entry.author,
      versions: entry.versions,
      tags: entry.tags,
      next: entry.next,
      draft: entry.draft,
      body: entry.body,
      toc: entry.toc,
      source: () => entry.getText('raw'),
      markdown: async () => withoutFrontmatter(await entry.getText('raw')),
    };
  })
  .sort((a, b) => b.date.localeCompare(a.date) || a.title.localeCompare(b.title));

/**
 * Whether drafts have pages: everywhere but the production site (the one selling through Paddle's production
 * environment), so a draft can be read locally and in the sandbox before it is published. Outside production a draft
 * is listed, marked as one; it is never fed, put in the sitemap or copied to dev.to, and no page is indexed there
 * (robots.ts).
 */
export function draftsShown(): boolean {
  return publicConfig().paddle.environment !== 'production';
}

/** The published posts, newest first. */
export function publishedPosts(): Post[] {
  return all.filter((post) => !post.draft);
}

/** The posts this environment has pages for, newest first: drafts too, outside production. */
export function postsWithPages(): Post[] {
  return draftsShown() ? all : publishedPosts();
}

export function getPost(slug: string): Post | undefined {
  return postsWithPages().find((post) => post.slug === slug);
}

function withoutFrontmatter(text: string): string {
  return text.replace(/^---\r?\n[\s\S]*?\r?\n---\r?\n/, '').trimStart();
}
