import { loader } from 'fumadocs-core/source';
// Generated by fumadocs-mdx into the project root `.source` (see source.config.ts).
import { docs } from '../../.source/server';

export const source = loader({
  baseUrl: '/docs',
  source: docs.toFumadocsSource(),
});
